language: php
php:
  - '5.6'
  - '7.4'
  - '8.3'

install:
  - composer install

jobs:
  include:
    - stage: Tests
      name: "Unit Tests"
      script: composer run test-unit
    - stage: Tests
      name: "Infection Tests"
      script: composer run infection
    - stage: Code Style
      name: "Code Style Check"
      script: composer run cs
    - stage: Static Analysis
      name: "Static Code Analysis"
      script: composer run phpstan
