name: PHP CI

on: [push, pull_request]

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpunit, xdebug
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run Coding Standards Check
      run: composer run cs

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpunit, xdebug
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run PHPStan
      run: composer run phpstan

  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpunit, xdebug
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run PHPUnit Tests
      run: composer run phpunit

  infection:
    name: Infection PHP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpunit, xdebug
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run Infection PHP
      run: composer run infection
